package com.bulbasaur.dat256.services.firebase;

import android.util.Log;

import com.google.firebase.firestore.CollectionReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.QuerySnapshot;

import java.util.ArrayList;
import java.util.List;

/**
 * @author ludwighultqvist
 * a class that implements the Collection interface
 */
class Collection implements DBCollection {

    private CollectionReference collection;

    /**
     * package private constructor that initializes the object with a reference to the
     * firebase-collection from the given root.
     * an instance should not be able to be directly created from outside the package
     * @param root the root string
     */
    Collection(String root) {
        this(FirebaseFirestore.getInstance().collection(root));
    }

    /**
     * package private constructor that initializes the object with a given reference to a
     * firebase-collection.
     * an instance should not be able to be directly created from outside the package
     * @param collection the CollectionReference object
     */
    Collection(CollectionReference collection) {
        this.collection = collection;
    }

    /**
     * creates a new document in the collection with an autogenerated id
     * @return a new DBDocument object
     */
    @Override
    public DBDocument create() {
        return new Document(collection.document());
    }

    /**
     * creates a new document in the collection with a given id (should be generated)
     * @param id the given id string
     * @return a new DBDocument object
     */
    @Override
    public DBDocument create(String id) {
        return new Document(collection.document(id));
    }

    /**
     * fetches a document with the given id from the collection in the database.
     * if no document is found, null is returned
     * @param id the given id string
     * @return the DBDocument found
     */
    @Override
    public DBDocument get(String id) {
        Log.d("COLLECTION", "Getting document: " + id + " from collection: " + collection.getPath());
        Document result = new Document();

        collection.document(id).get()
                .addOnCompleteListener(task -> {
                    if (task.isSuccessful()) {
                        Log.d("COLLECTION", "Getting document succeeded");
                        DocumentSnapshot snapshot = task.getResult();
                        if (snapshot != null && snapshot.exists()) {
                            result.init(snapshot.getReference());
                        }
                    }
                })
                .addOnFailureListener(e -> {});

        return result.isEmpty() ? null : result;
    }

    /**
     * fetches and returns a list of all documents from the collection in the database
     * @return the list of DBDocument objects
     */
    @Override
    public List<? extends DBDocument> all() {
        Log.d("COLLECTION", "Getting all documents from " + collection.getPath());
        List<Document> result = new ArrayList<>();

        collection.get()
                .addOnCompleteListener(task -> {
                    if (task.isSuccessful()) {
                        Log.d("COLLECTION", "Getting all documents succeeded");
                        QuerySnapshot snapshot = task.getResult();

                        if (snapshot != null) {
                            for (DocumentSnapshot document : snapshot.getDocuments()) {
                                result.add(new Document(document.getReference()));
                            }
                        }
                    }
                })
                .addOnFailureListener(e -> {});

        return result;
    }
}
