package com.bulbasaur.dat256.services.firebase;

import android.support.annotation.NonNull;

import java.util.List;

/**
 * @author ludwighultqvist
 * interface that acts as a collection stored in the database.
 * e.g. collection of users, meetups, groups etc.
 */
public interface DBCollection {

    /**
     * creates a new document in the collection with a given id (should be generated)
     * @param id the given id string
     * @return a new DBDocument object
     */
    DBDocument create(String id);

    /**
     * creates a new document in the collection with an autogenerated id
     * @return a new DBDocument object
     */
    DBDocument create();

    /**
     * fetches a document with the given id from the collection in the database.
     * if no document is found, null is returned
     * @param id the given id string
     * @param listener the listener of the request
     * @return the DBDocument found
     */
    DBDocument get(String id, @NonNull RequestListener<DBDocument> listener);

    /**
     * fetches all documents from the collection in the database
     * @param listener the listener of the request
     * @return the list of documents
     */
    List<? extends DBDocument> all(@NonNull RequestListener<List<? extends DBDocument>> listener);


    /**
     * searches the documents of the collection according to given filter and returns the documents
     * that matches
     * @param queryFilter the filter object
     * @param listener the listener of the request
     * @return the list of documents
     */
    List<? extends DBDocument> search(QueryFilter queryFilter, @NonNull RequestListener<List<? extends DBDocument>> listener);

    /**
     * creates and returns a runnable tester of the document.
     * @return the runnable object
     */
    Runnable tester();
}
