package com.bulbasaur.dat256.services.firebase;

import android.support.annotation.NonNull;

import java.util.List;

/**
 * @author ludwighultqvist
 * interface that acts as a collection stored in the database.
 * e.g. collection of users, meetups, groups etc.
 */
public interface DBCollection {

    DBDocument create(String id, RequestListener<DBDocument> listener);

    /**
     * creates a new document in the collection with a given id (should be generated)
     * @param id the given id string
     * @return a new DBDocument object
     */
    DBDocument create(String id);

    DBDocument create(RequestListener<DBDocument> listener);

    /**
     * creates a new document in the collection with an autogenerated id
     * @return a new DBDocument object
     */
    DBDocument create();

    DBDocument get(String id, @NonNull RequestListener<DBDocument> listener);

    /**
     * fetches a document with the given id from the collection in the database.
     * if no document is found, null is returned
     * @param id the given id string
     * @return the DBDocument found
     */
    DBDocument get(String id);

    List<? extends DBDocument> all(@NonNull RequestListener<List<? extends DBDocument>> listener);

    /**
     * fetches and returns a list of all documents from the collection in the database
     * @return the list of DBDocument objects
     */
    List<? extends DBDocument> all();

    List<? extends DBDocument> search(List<QueryFilter> filters, @NonNull RequestListener<List<? extends DBDocument>> listener);

    List<? extends DBDocument> search(List<QueryFilter> filters);

    List<? extends DBDocument> search(QueryFilter filter, @NonNull RequestListener<List<? extends DBDocument>> listener);

    List<? extends DBDocument> search(QueryFilter filter);

    Runnable tester();
}
